version: '3'

services:
  openserp:
    container_name: serp
    build:
      context: .
    ports: 
      - 7001:7000  # Maps port 7001 on the host to port 7000 in the container
    command: serve -l
    #volumes:
    #  - ./config.yaml:/usr/src/app/config.yaml
    environment:
      OPENSERP_APP_HOST: "0.0.0.0"
      OPENSERP_APP_PORT: 7000
      OPENSERP_BAIDU_RATE_REQUESTS: 6   # Number of requests per Minute
      OPENSERP_BAIDU_RATE_BURST: 2      # Number of non-ratelimited requests per Minute
